"use strict";
const { fs, path, clean, number, readCsv, escapeHtml, phoneHref } = require("./lib");
const root = path.join(__dirname, ".."); const output = path.join(root, "output"); const inputFile = path.join(output, "sales-leads.csv"); const reportFile = path.join(output, "sales-dashboard.html");
if (!fs.existsSync(inputFile)) throw new Error("Falta sales-leads.csv. Ejecuta npm run score antes.");
const leads = readCsv(inputFile).sort((a, b) => number(b.salesScore) - number(a.salesScore)); const labels = { no_website_verified: "Sin web verificada", website_not_found: "Sin web indicada · verificar", social_only: "Solo redes sociales", directory_only: "Solo directorio", website_found: "Web propia encontrada", invalid_url: "URL no válida" }; const priorities = { CONTACT_NOW: "CONTACTAR AHORA", REVIEW_FIRST: "REVISAR PRIMERO", LOW_PRIORITY: "PRIORIDAD BAJA" };
function link(href, label) { return href ? `<a href="${escapeHtml(href)}" target="_blank" rel="noopener">${label}</a>` : ""; }
function card(lead, index) { const phone = lead.phone ? link(`tel:${phoneHref(lead.phone)}`, "Llamar") : ""; const web = lead.website ? link(lead.website, "Abrir web") : ""; return `<article class="lead ${escapeHtml(lead.salesPriority)}" data-priority="${escapeHtml(lead.salesPriority)}" data-search="${escapeHtml(`${lead.name} ${lead.category}`.toLowerCase())}"><div class="top"><span>#${index + 1}</span><b>${escapeHtml(priorities[lead.salesPriority])}</b><strong>${escapeHtml(lead.salesScore)}/100</strong></div><h2>${escapeHtml(lead.name)}</h2><p>${escapeHtml(lead.category || "Categoría no indicada")} · ★ ${escapeHtml(lead.rating || "—")} · ${escapeHtml(lead.reviews || 0)} reseñas</p><span class="status">${escapeHtml(labels[lead.websiteStatus] || lead.websiteStatus)}</span><h3>Motivo</h3><p>${escapeHtml(lead.salesReason)}</p><h3>Ángulo de venta</h3><p>${escapeHtml(lead.salesAngle)}</p><h3>Producto recomendado</h3><p><strong>${escapeHtml(lead.recommendedProduct)}</strong></p><p class="audit">${lead.websiteScore !== "" ? `Web técnica: ${escapeHtml(lead.websiteScore)}/100 · ${escapeHtml(lead.websiteQuality)}` : "Web técnica: no aplicable"}</p><div class="actions">${link(lead.googleMapsUrl, "Google Maps")}${phone}${web}</div></article>`; }
const counts = Object.fromEntries(["CONTACT_NOW", "REVIEW_FIRST", "LOW_PRIORITY"].map((priority) => [priority, leads.filter((lead) => lead.salesPriority === priority).length]));
const html = `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Warrior Code — Sales Dashboard</title><style>body{margin:0;background:#0b1020;color:#e9ecf8;font:15px system-ui}.shell{max-width:1250px;margin:auto;padding:32px 20px}h1{font-size:38px;margin:4px 0}.muted,p{color:#aab4cf}.metrics,.grid{display:grid;gap:14px}.metrics{grid-template-columns:repeat(4,1fr);margin:22px 0}.metric,.lead{background:#141b32;border:1px solid #2c385a;border-radius:16px;padding:18px}.metric b{display:block;font-size:28px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.lead.CONTACT_NOW{border-top:3px solid #fbbf24}.lead.REVIEW_FIRST{border-top:3px solid #fb923c}.top{display:flex;gap:10px;align-items:center}.top strong{margin-left:auto;font-size:25px}.status,b{color:#c4b5fd}.lead h2{margin-bottom:5px}.lead h3{font-size:11px;text-transform:uppercase;color:#91a2cc;margin:18px 0 4px}.audit{border-top:1px solid #2c385a;padding-top:12px}.actions{display:flex;gap:9px;flex-wrap:wrap}.actions a{color:#eaf3ff;border:1px solid #405589;border-radius:8px;padding:7px 10px;text-decoration:none}.tools{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:18px}input,button{padding:10px;border-radius:8px;border:1px solid #405589;background:#141b32;color:white}button{cursor:pointer}@media(max-width:760px){.metrics,.grid{grid-template-columns:1fr}}</style><main class="shell"><span class="muted">Warrior Code · Prospección comercial</span><h1>¿A quién contactar primero?</h1><p>Prioridad basada en demanda, necesidad digital y posibilidad de contacto; no solo en calidad técnica.</p><section class="metrics"><div class="metric"><b>${leads.length}</b>negocios analizados</div><div class="metric"><b>${counts.CONTACT_NOW}</b>contactar ahora</div><div class="metric"><b>${counts.REVIEW_FIRST}</b>revisar primero</div><div class="metric"><b>${leads.filter((lead) => ["no_website_verified", "website_not_found", "social_only", "directory_only"].includes(lead.websiteStatus)).length}</b>necesidad digital visible</div></section><section class="tools"><input id="search" placeholder="Buscar negocio o categoría"><button data-filter="ALL">Todos</button><button data-filter="CONTACT_NOW">Contactar ahora</button><button data-filter="REVIEW_FIRST">Revisar</button></section><section class="grid">${leads.map(card).join("")}</section></main><script>let f='ALL';const c=[...document.querySelectorAll('.lead')],s=document.querySelector('#search');function u(){const q=s.value.toLowerCase();c.forEach(x=>x.hidden=!((f==='ALL'||x.dataset.priority===f)&&x.dataset.search.includes(q)))}document.querySelectorAll('button').forEach(b=>b.onclick=()=>{f=b.dataset.filter;u()});s.oninput=u;</script>`;
fs.writeFileSync(reportFile, html, "utf8"); console.log(`Dashboard generado: ${reportFile}`);
