"use strict";
const { fs, path, clean, normalizeUrl, readCsv, writeCsv } = require("./lib");
const root = path.join(__dirname, ".."); const output = path.join(root, "output"); const inputFile = path.join(output, "website-discovery.csv"); const outputFile = path.join(output, "website-analysis.csv");
const columns = ["leadId", "name", "category", "rating", "reviews", "phone", "website", "websiteType", "websiteStatus", "discoverySource", "discoveryConfidence", "discoveryVerified", "discoveryNote", "address", "city", "state", "country", "googleMapsUrl", "businessScore", "businessReason", "preliminaryOpportunityScore", "preliminaryOpportunityLevel", "preliminaryOpportunityReason", "websiteAuditStatus", "httpStatus", "finalUrl", "redirectDetected", "hasHttps", "title", "metaDescription", "hasViewport", "hasPhone", "hasEmail", "hasWhatsapp", "hasForm", "socialLinks", "detectedEmails", "detectedPhones", "contentLength", "websiteScore", "websiteQuality", "websiteIssues", "error"];
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function attr(tag, name) { const match = tag.match(new RegExp(`\\b${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s>]+))`, "i")); return match ? (match[1] || match[2] || match[3] || "") : ""; }
function strip(html) { return html.replace(/<script\b[\s\S]*?<\/script>/gi, " ").replace(/<style\b[\s\S]*?<\/style>/gi, " ").replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim(); }
function analyseHtml(html) {
  const title = (html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i) || [])[1] || ""; const tags = html.match(/<meta\b[^>]*>/gi) || [];
  const meta = tags.find((tag) => ["description", "og:description"].includes(attr(tag, "name").toLowerCase()) || attr(tag, "property").toLowerCase() === "og:description");
  const viewport = tags.some((tag) => attr(tag, "name").toLowerCase() === "viewport");
  const emails = [...new Set([...html.matchAll(/(?:mailto:|\b)([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})(?=["'\s<]|$)/gi)].map((match) => match[1].toLowerCase()))].slice(0, 5);
  const phones = [...new Set([...html.matchAll(/href\s*=\s*(["'])\s*tel:([^"'#?\s]+)\1/gi)].map((match) => match[2].replace(/^\+?34/, "+34 ").replace(/[^+\d ]/g, "").trim()).filter(Boolean))].slice(0, 5);
  const social = ["facebook", "instagram", "linkedin", "youtube", "tiktok", "twitter"].filter((name) => new RegExp(`${name}\\.com`, "i").test(html));
  return { title: strip(title), metaDescription: meta ? attr(meta, "content") : "", hasViewport: viewport, hasPhone: phones.length > 0, hasEmail: emails.length > 0, hasWhatsapp: /(?:wa\.me\/|api\.whatsapp\.com|web\.whatsapp\.com|whatsapp:\/\/)/i.test(html), hasForm: /<form\b/i.test(html), socialLinks: social.join(";"), detectedEmails: emails.join(";"), detectedPhones: phones.join(";"), contentLength: strip(html).length };
}
function score(result) { if (result.websiteAuditStatus !== "analysed") return ""; let value = 0; if (result.httpStatus >= 200 && result.httpStatus < 400) value += 20; if (result.hasHttps) value += 15; if (result.title) value += 10; if (result.metaDescription) value += 10; if (result.hasViewport) value += 15; if (result.hasPhone) value += 10; if (result.hasEmail) value += 5; if (result.hasWhatsapp) value += 5; if (result.hasForm) value += 5; if (result.socialLinks) value += 5; return value; }
function quality(value) { return value === "" ? "NOT_APPLICABLE" : value >= 80 ? "GOOD" : value >= 60 ? "OK" : value >= 35 ? "WEAK" : "POOR"; }
function issues(result) { if (result.websiteAuditStatus !== "analysed") return result.error ? `No se pudo analizar: ${result.error}` : ""; const list = []; if (!result.hasHttps) list.push("sin HTTPS"); if (!result.title) list.push("sin title"); if (!result.metaDescription) list.push("sin meta description"); if (!result.hasViewport) list.push("sin viewport móvil"); if (!result.hasPhone) list.push("sin teléfono visible"); if (!result.hasEmail) list.push("sin email visible"); if (!result.hasWhatsapp) list.push("sin WhatsApp"); if (!result.hasForm) list.push("sin formulario"); return list.join(" · "); }
async function check(lead) {
  const result = { ...lead, websiteAuditStatus: "not_applicable", httpStatus: "", finalUrl: "", redirectDetected: false, hasHttps: false, title: "", metaDescription: "", hasViewport: false, hasPhone: false, hasEmail: false, hasWhatsapp: false, hasForm: false, socialLinks: "", detectedEmails: "", detectedPhones: "", contentLength: 0, websiteScore: "", websiteQuality: "NOT_APPLICABLE", websiteIssues: "", error: "" };
  if (lead.websiteStatus !== "website_found" || lead.websiteType !== "own_website") return result;
  const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 15000);
  try { const response = await fetch(normalizeUrl(lead.website), { redirect: "follow", signal: controller.signal, headers: { "User-Agent": "WarriorCodeProspecting/4.0", Accept: "text/html,application/xhtml+xml" } }); const type = response.headers.get("content-type") || ""; const html = /text\/html|application\/xhtml\+xml/i.test(type) ? await response.text() : ""; Object.assign(result, analyseHtml(html), { websiteAuditStatus: response.ok ? "analysed" : "failed", httpStatus: response.status, finalUrl: response.url, redirectDetected: response.url !== normalizeUrl(lead.website), hasHttps: response.url.startsWith("https://") }); if (!response.ok) result.error = `HTTP ${response.status}`; } catch (error) { result.websiteAuditStatus = "failed"; result.error = error.name === "AbortError" ? "timeout" : clean(error.message); } finally { clearTimeout(timer); }
  result.websiteScore = score(result); result.websiteQuality = quality(result.websiteScore); result.websiteIssues = issues(result); return result;
}
if (!fs.existsSync(inputFile)) throw new Error("Falta website-discovery.csv. Ejecuta npm run discover antes.");
(async () => { const leads = readCsv(inputFile); const results = []; for (const [index, lead] of leads.entries()) { console.log(`[${index + 1}/${leads.length}] ${lead.name}`); results.push(await check(lead)); if (index < leads.length - 1) await sleep(500); } writeCsv(outputFile, results, columns); console.log(`Auditoría completada: ${results.filter((lead) => lead.websiteAuditStatus === "analysed").length} webs propias analizadas.`); })().catch((error) => { console.error(error); process.exit(1); });
